### ISSUE TITLE
Got an error in XCode 8

### ISSUE THREAD

**Issue by markolofsen** [petejkim/metamask-mobile#5]
Got an error in XCode 8 when trying to start App

```
Loading dependency graph...2018-03-01 00:31 node[77323] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-03-01 00:31 node[77323] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-03-01 00:31 node[77323] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"errno":"EMFILE","code":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1003:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1382:9)

```

**Comment by BroderickHigby** [comment]
I have the same problem, what fixed this error?
